name: Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js and cache
        uses: ./.github/actions/nodejs

      - name: Build the package
        if: ${{ env.IS_MAIN == 'true' }}
        run: npm run build

concurrency:
  group: build-${{ github.head_ref }}
  cancel-in-progress: true
